title: Code4Projects
email: sasadangelo@gmail.com
description: What I have learned after 30 years of programming
baseurl: "/code4projects"
url: ""

# Typography configuration
fonts:
    size: 30px
    family: Roboto Slab

collections:
  authors:
    output: true

# Code Highlighter
## 'pygments' is unsupported on GitHub Pages now.
highlighter: rouge
highlight:
  line_number: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

sidebars:
  course_sidebar

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude: [utility]
