title: Code4Projects
email: sasadangelo@gmail.com
description: What I have learned after 30 years of programming
baseurl: "/code4projects"
url: "https://sasadangelo.github.io"

# Typography configuration
fonts:
    size: 30px
    family: Roboto Slab

collections:
  authors:
    output: true

# Code Highlighter
## 'pygments' is unsupported on GitHub Pages now.
highlighter: rouge
highlight:
  line_number: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:slug
  - scope:
      path: ""
    values:
      layout: "default"

paginate_path: "/blog/page:num/"
pagination:
  enabled: true
  per_page: 3
  sort_reverse: true
  sort_field: 'date'
  title: ':title (page :num)'
  indexpage: 'index'
  trail:
    before: 2
    after: 2

sidebars:
  post_sidebar

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2

exclude: [utility]
